-- Fixes de constraints @unique → @@unique([tenant_id, campo])
ALTER TABLE conceptos_tesoreria DROP CONSTRAINT IF EXISTS "conceptos_tesoreria_codigo_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='conceptos_tesoreria_tenant_id_codigo_key') THEN ALTER TABLE conceptos_tesoreria ADD CONSTRAINT "conceptos_tesoreria_tenant_id_codigo_key" UNIQUE (tenant_id, codigo); END IF; END $$;
ALTER TABLE tipos_socio DROP CONSTRAINT IF EXISTS "tipos_socio_codigo_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='tipos_socio_tenant_id_codigo_key') THEN ALTER TABLE tipos_socio ADD CONSTRAINT "tipos_socio_tenant_id_codigo_key" UNIQUE (tenant_id, codigo); END IF; END $$;
ALTER TABLE categorias_socio DROP CONSTRAINT IF EXISTS "categorias_socio_codigo_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='categorias_socio_tenant_id_codigo_key') THEN ALTER TABLE categorias_socio ADD CONSTRAINT "categorias_socio_tenant_id_codigo_key" UNIQUE (tenant_id, codigo); END IF; END $$;
ALTER TABLE estados_socio DROP CONSTRAINT IF EXISTS "estados_socio_codigo_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='estados_socio_tenant_id_codigo_key') THEN ALTER TABLE estados_socio ADD CONSTRAINT "estados_socio_tenant_id_codigo_key" UNIQUE (tenant_id, codigo); END IF; END $$;
ALTER TABLE socios DROP CONSTRAINT IF EXISTS "socios_nro_socio_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='socios_tenant_id_nro_socio_key') THEN ALTER TABLE socios ADD CONSTRAINT "socios_tenant_id_nro_socio_key" UNIQUE (tenant_id, nro_socio); END IF; END $$;
ALTER TABLE socios DROP CONSTRAINT IF EXISTS "socios_rfid_uid_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='socios_tenant_id_rfid_uid_key') THEN ALTER TABLE socios ADD CONSTRAINT "socios_tenant_id_rfid_uid_key" UNIQUE (tenant_id, rfid_uid); END IF; END $$;
ALTER TABLE cobradores DROP CONSTRAINT IF EXISTS "cobradores_codigo_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='cobradores_tenant_id_codigo_key') THEN ALTER TABLE cobradores ADD CONSTRAINT "cobradores_tenant_id_codigo_key" UNIQUE (tenant_id, codigo); END IF; END $$;
ALTER TABLE actividades DROP CONSTRAINT IF EXISTS "actividades_codigo_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='actividades_tenant_id_codigo_key') THEN ALTER TABLE actividades ADD CONSTRAINT "actividades_tenant_id_codigo_key" UNIQUE (tenant_id, codigo); END IF; END $$;
ALTER TABLE categorias_actividad DROP CONSTRAINT IF EXISTS "categorias_actividad_codigo_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='categorias_actividad_tenant_id_codigo_key') THEN ALTER TABLE categorias_actividad ADD CONSTRAINT "categorias_actividad_tenant_id_codigo_key" UNIQUE (tenant_id, codigo); END IF; END $$;
ALTER TABLE medios_pago DROP CONSTRAINT IF EXISTS "medios_pago_codigo_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='medios_pago_tenant_id_codigo_key') THEN ALTER TABLE medios_pago ADD CONSTRAINT "medios_pago_tenant_id_codigo_key" UNIQUE (tenant_id, codigo); END IF; END $$;
ALTER TABLE pagos DROP CONSTRAINT IF EXISTS "pagos_numero_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='pagos_tenant_id_numero_key') THEN ALTER TABLE pagos ADD CONSTRAINT "pagos_tenant_id_numero_key" UNIQUE (tenant_id, numero); END IF; END $$;
ALTER TABLE configuracion_debito DROP CONSTRAINT IF EXISTS "configuracion_debito_codigo_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='configuracion_debito_tenant_id_codigo_key') THEN ALTER TABLE configuracion_debito ADD CONSTRAINT "configuracion_debito_tenant_id_codigo_key" UNIQUE (tenant_id, codigo); END IF; END $$;
ALTER TABLE archivos_debito DROP CONSTRAINT IF EXISTS "archivos_debito_numero_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='archivos_debito_tenant_id_numero_key') THEN ALTER TABLE archivos_debito ADD CONSTRAINT "archivos_debito_tenant_id_numero_key" UNIQUE (tenant_id, numero); END IF; END $$;
ALTER TABLE importaciones_cobranza DROP CONSTRAINT IF EXISTS "importaciones_cobranza_numero_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='importaciones_cobranza_tenant_id_numero_key') THEN ALTER TABLE importaciones_cobranza ADD CONSTRAINT "importaciones_cobranza_tenant_id_numero_key" UNIQUE (tenant_id, numero); END IF; END $$;
ALTER TABLE transferencias_caja DROP CONSTRAINT IF EXISTS "transferencias_caja_numero_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='transferencias_caja_tenant_id_numero_key') THEN ALTER TABLE transferencias_caja ADD CONSTRAINT "transferencias_caja_tenant_id_numero_key" UNIQUE (tenant_id, numero); END IF; END $$;
ALTER TABLE cuentas_contables DROP CONSTRAINT IF EXISTS "cuentas_contables_codigo_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='cuentas_contables_tenant_id_codigo_key') THEN ALTER TABLE cuentas_contables ADD CONSTRAINT "cuentas_contables_tenant_id_codigo_key" UNIQUE (tenant_id, codigo); END IF; END $$;
ALTER TABLE asientos DROP CONSTRAINT IF EXISTS "asientos_numero_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='asientos_tenant_id_numero_key') THEN ALTER TABLE asientos ADD CONSTRAINT "asientos_tenant_id_numero_key" UNIQUE (tenant_id, numero); END IF; END $$;
ALTER TABLE movimientos_caja DROP CONSTRAINT IF EXISTS "movimientos_caja_numero_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='movimientos_caja_tenant_id_numero_key') THEN ALTER TABLE movimientos_caja ADD CONSTRAINT "movimientos_caja_tenant_id_numero_key" UNIQUE (tenant_id, numero); END IF; END $$;
ALTER TABLE formatos_extracto DROP CONSTRAINT IF EXISTS "formatos_extracto_nombre_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='formatos_extracto_tenant_id_nombre_key') THEN ALTER TABLE formatos_extracto ADD CONSTRAINT "formatos_extracto_tenant_id_nombre_key" UNIQUE (tenant_id, nombre); END IF; END $$;
ALTER TABLE extractos_bancarios DROP CONSTRAINT IF EXISTS "extractos_bancarios_numero_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='extractos_bancarios_tenant_id_numero_key') THEN ALTER TABLE extractos_bancarios ADD CONSTRAINT "extractos_bancarios_tenant_id_numero_key" UNIQUE (tenant_id, numero); END IF; END $$;
ALTER TABLE echeqs DROP CONSTRAINT IF EXISTS "echeqs_numero_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='echeqs_tenant_id_numero_key') THEN ALTER TABLE echeqs ADD CONSTRAINT "echeqs_tenant_id_numero_key" UNIQUE (tenant_id, numero); END IF; END $$;
ALTER TABLE links_pago DROP CONSTRAINT IF EXISTS "links_pago_codigo_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='links_pago_tenant_id_codigo_key') THEN ALTER TABLE links_pago ADD CONSTRAINT "links_pago_tenant_id_codigo_key" UNIQUE (tenant_id, codigo); END IF; END $$;
ALTER TABLE cargos_personal DROP CONSTRAINT IF EXISTS "cargos_personal_codigo_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='cargos_personal_tenant_id_codigo_key') THEN ALTER TABLE cargos_personal ADD CONSTRAINT "cargos_personal_tenant_id_codigo_key" UNIQUE (tenant_id, codigo); END IF; END $$;
ALTER TABLE entidades DROP CONSTRAINT IF EXISTS "entidades_codigo_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='entidades_tenant_id_codigo_key') THEN ALTER TABLE entidades ADD CONSTRAINT "entidades_tenant_id_codigo_key" UNIQUE (tenant_id, codigo); END IF; END $$;
ALTER TABLE ordenes_compra DROP CONSTRAINT IF EXISTS "ordenes_compra_numero_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='ordenes_compra_tenant_id_numero_key') THEN ALTER TABLE ordenes_compra ADD CONSTRAINT "ordenes_compra_tenant_id_numero_key" UNIQUE (tenant_id, numero); END IF; END $$;
ALTER TABLE pedidos DROP CONSTRAINT IF EXISTS "pedidos_numero_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='pedidos_tenant_id_numero_key') THEN ALTER TABLE pedidos ADD CONSTRAINT "pedidos_tenant_id_numero_key" UNIQUE (tenant_id, numero); END IF; END $$;
ALTER TABLE categorias_producto DROP CONSTRAINT IF EXISTS "categorias_producto_codigo_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='categorias_producto_tenant_id_codigo_key') THEN ALTER TABLE categorias_producto ADD CONSTRAINT "categorias_producto_tenant_id_codigo_key" UNIQUE (tenant_id, codigo); END IF; END $$;
ALTER TABLE productos DROP CONSTRAINT IF EXISTS "productos_codigo_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='productos_tenant_id_codigo_key') THEN ALTER TABLE productos ADD CONSTRAINT "productos_tenant_id_codigo_key" UNIQUE (tenant_id, codigo); END IF; END $$;
ALTER TABLE producto_variantes DROP CONSTRAINT IF EXISTS "producto_variantes_sku_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='producto_variantes_tenant_id_sku_key') THEN ALTER TABLE producto_variantes ADD CONSTRAINT "producto_variantes_tenant_id_sku_key" UNIQUE (tenant_id, sku); END IF; END $$;
ALTER TABLE movimientos_contables DROP CONSTRAINT IF EXISTS "movimientos_contables_numero_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='movimientos_contables_tenant_id_numero_key') THEN ALTER TABLE movimientos_contables ADD CONSTRAINT "movimientos_contables_tenant_id_numero_key" UNIQUE (tenant_id, numero); END IF; END $$;
ALTER TABLE conceptos_liquidacion DROP CONSTRAINT IF EXISTS "conceptos_liquidacion_codigo_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='conceptos_liquidacion_tenant_id_codigo_key') THEN ALTER TABLE conceptos_liquidacion ADD CONSTRAINT "conceptos_liquidacion_tenant_id_codigo_key" UNIQUE (tenant_id, codigo); END IF; END $$;
ALTER TABLE liquidaciones_sueldo DROP CONSTRAINT IF EXISTS "liquidaciones_sueldo_numero_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='liquidaciones_sueldo_tenant_id_numero_key') THEN ALTER TABLE liquidaciones_sueldo ADD CONSTRAINT "liquidaciones_sueldo_tenant_id_numero_key" UNIQUE (tenant_id, numero); END IF; END $$;
ALTER TABLE tipos_espacio DROP CONSTRAINT IF EXISTS "tipos_espacio_codigo_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='tipos_espacio_tenant_id_codigo_key') THEN ALTER TABLE tipos_espacio ADD CONSTRAINT "tipos_espacio_tenant_id_codigo_key" UNIQUE (tenant_id, codigo); END IF; END $$;
ALTER TABLE espacios_deportivos DROP CONSTRAINT IF EXISTS "espacios_deportivos_codigo_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='espacios_deportivos_tenant_id_codigo_key') THEN ALTER TABLE espacios_deportivos ADD CONSTRAINT "espacios_deportivos_tenant_id_codigo_key" UNIQUE (tenant_id, codigo); END IF; END $$;
ALTER TABLE centros_costo DROP CONSTRAINT IF EXISTS "centros_costo_codigo_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='centros_costo_tenant_id_codigo_key') THEN ALTER TABLE centros_costo ADD CONSTRAINT "centros_costo_tenant_id_codigo_key" UNIQUE (tenant_id, codigo); END IF; END $$;
ALTER TABLE noticias DROP CONSTRAINT IF EXISTS "noticias_slug_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='noticias_tenant_id_slug_key') THEN ALTER TABLE noticias ADD CONSTRAINT "noticias_tenant_id_slug_key" UNIQUE (tenant_id, slug); END IF; END $$;
ALTER TABLE categorias_menu DROP CONSTRAINT IF EXISTS "categorias_menu_codigo_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='categorias_menu_tenant_id_codigo_key') THEN ALTER TABLE categorias_menu ADD CONSTRAINT "categorias_menu_tenant_id_codigo_key" UNIQUE (tenant_id, codigo); END IF; END $$;
ALTER TABLE comandas DROP CONSTRAINT IF EXISTS "comandas_numero_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='comandas_tenant_id_numero_key') THEN ALTER TABLE comandas ADD CONSTRAINT "comandas_tenant_id_numero_key" UNIQUE (tenant_id, numero); END IF; END $$;
ALTER TABLE sectores_buffet DROP CONSTRAINT IF EXISTS "sectores_buffet_codigo_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='sectores_buffet_tenant_id_codigo_key') THEN ALTER TABLE sectores_buffet ADD CONSTRAINT "sectores_buffet_tenant_id_codigo_key" UNIQUE (tenant_id, codigo); END IF; END $$;
ALTER TABLE impresoras_termicas DROP CONSTRAINT IF EXISTS "impresoras_termicas_nombre_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='impresoras_termicas_tenant_id_nombre_key') THEN ALTER TABLE impresoras_termicas ADD CONSTRAINT "impresoras_termicas_tenant_id_nombre_key" UNIQUE (tenant_id, nombre); END IF; END $$;
ALTER TABLE dispositivos_acceso DROP CONSTRAINT IF EXISTS "dispositivos_acceso_codigo_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='dispositivos_acceso_tenant_id_codigo_key') THEN ALTER TABLE dispositivos_acceso ADD CONSTRAINT "dispositivos_acceso_tenant_id_codigo_key" UNIQUE (tenant_id, codigo); END IF; END $$;
ALTER TABLE eventos DROP CONSTRAINT IF EXISTS "eventos_codigo_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='eventos_tenant_id_codigo_key') THEN ALTER TABLE eventos ADD CONSTRAINT "eventos_tenant_id_codigo_key" UNIQUE (tenant_id, codigo); END IF; END $$;
ALTER TABLE entradas DROP CONSTRAINT IF EXISTS "entradas_codigo_key";
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='entradas_tenant_id_codigo_key') THEN ALTER TABLE entradas ADD CONSTRAINT "entradas_tenant_id_codigo_key" UNIQUE (tenant_id, codigo); END IF; END $$;
-- Drop old single-column unique indexes (replaced by tenant-scoped composite ones)
DROP INDEX IF EXISTS actividades_codigo_key;
DROP INDEX IF EXISTS archivos_debito_numero_key;
DROP INDEX IF EXISTS asientos_numero_key;
DROP INDEX IF EXISTS cargos_personal_codigo_key;
DROP INDEX IF EXISTS categorias_actividad_codigo_key;
DROP INDEX IF EXISTS categorias_menu_codigo_key;
DROP INDEX IF EXISTS categorias_producto_codigo_key;
DROP INDEX IF EXISTS categorias_socio_codigo_key;
DROP INDEX IF EXISTS centros_costo_codigo_key;
DROP INDEX IF EXISTS cobradores_codigo_key;
DROP INDEX IF EXISTS comandas_numero_key;
DROP INDEX IF EXISTS conceptos_liquidacion_codigo_key;
DROP INDEX IF EXISTS conceptos_tesoreria_codigo_key;
DROP INDEX IF EXISTS configuracion_debito_codigo_key;
DROP INDEX IF EXISTS configuracion_fiscal_cuit_key;
DROP INDEX IF EXISTS cuentas_contables_codigo_key;
DROP INDEX IF EXISTS dispositivos_acceso_codigo_key;
DROP INDEX IF EXISTS echeqs_numero_key;
DROP INDEX IF EXISTS entidades_codigo_key;
DROP INDEX IF EXISTS entradas_codigo_key;
DROP INDEX IF EXISTS espacios_deportivos_codigo_key;
DROP INDEX IF EXISTS estados_socio_codigo_key;
DROP INDEX IF EXISTS eventos_codigo_key;
DROP INDEX IF EXISTS extractos_bancarios_numero_key;
DROP INDEX IF EXISTS formatos_extracto_nombre_key;
DROP INDEX IF EXISTS impresoras_termicas_nombre_key;
DROP INDEX IF EXISTS importaciones_cobranza_numero_key;
DROP INDEX IF EXISTS links_pago_codigo_key;
DROP INDEX IF EXISTS liquidaciones_sueldo_numero_key;
DROP INDEX IF EXISTS medios_pago_codigo_key;
DROP INDEX IF EXISTS movimientos_caja_numero_key;
DROP INDEX IF EXISTS movimientos_contables_numero_key;
DROP INDEX IF EXISTS noticias_slug_key;
DROP INDEX IF EXISTS ordenes_compra_numero_key;
DROP INDEX IF EXISTS pagos_numero_key;
DROP INDEX IF EXISTS pedidos_numero_key;
DROP INDEX IF EXISTS productos_codigo_key;
DROP INDEX IF EXISTS producto_variantes_sku_key;
DROP INDEX IF EXISTS sectores_buffet_codigo_key;
DROP INDEX IF EXISTS socios_nro_socio_key;
DROP INDEX IF EXISTS socios_rfid_uid_key;
DROP INDEX IF EXISTS tipos_espacio_codigo_key;
DROP INDEX IF EXISTS tipos_socio_codigo_key;
DROP INDEX IF EXISTS transferencias_caja_numero_key;
DROP INDEX IF EXISTS cajas_codigo_key;
DROP INDEX IF EXISTS mesas_numero_key;
